name: thinglybotstuff
favicon: null
layout_spectrum: 1
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eeffff'
    - '#030e22'
    - '#cd39a0'
    - '#3c71a0'
    - '#99c9d1'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose: []
